### ISSUE TITLE
Errors after setup

### ISSUE THREAD

**Issue by rizzla82** [althonos/InstaLooter#1]
Previously had Instraider working on the machine, had issues after upgrading to newer Firefox and upgraded to Ubuntu 16.04:

~/InstaLooter$ ./instaLooter.py -j 8-v -n 4000 test /home/user1/Pictures/intra/test/
./instaLooter.py: line 3: __author__: command not found
./instaLooter.py: line 4: __author_email__: command not found
./instaLooter.py: line 5: __version__: command not found
from: can't read /var/mail/contextlib
from: can't read /var/mail/bs4
./instaLooter.py: line 25: try:: command not found
./instaLooter.py: line 28: except: command not found
./instaLooter.py: line 29: PIL: command not found
./instaLooter.py: line 31: try:: command not found
./instaLooter.py: line 33: PARSER: command not found
./instaLooter.py: line 34: except: command not found
./instaLooter.py: line 35: PARSER: command not found
./instaLooter.py: line 37: syntax error near unexpected token `('
./instaLooter.py: line 37: `class InstaDownloader(threading.Thread):'

**Comment by althonos** [comment]
I forgot to add a shabang, just run instaLooter with "python -m instaLooter
[your args]" and it should work until I fix it :)

**Comment by rizzla82** [comment]
Hi Althonos,

Thanks for the quick response, work perfectly now.

Final questions your author and email information are included, does that need to be removed or updated?

Kind Regards
R

**Comment by althonos** [comment]
No, they are up-to-date and meant to be included for contact ! (they are on
my GitHub profile as well, so anyone could spam me it they really wanted
to) ;)

**Comment by rizzla82** [comment]
No Worries, understood.
