### ISSUE TITLE
can't save post to json

### ISSUE THREAD

**Issue by adamaulia** [althonos/InstaLooter#102]
Hi, 
I'm trying to save this post to json file 
https://www.instagram.com/p/BZXkRHqDOF8/?taken-by=natgeo

by using this command 
instaLooter post BZXkRHqDOF tes -D
or 
instaLooter post BZXkRHqDOF tes -d

both command I already try and show this , 
$ instaLooter post BZXkRHqDOF tes -d
Usage:
    instaLooter <profile> [<directory>] [options]
    instaLooter hashtag <hashtag> <directory> [options]
    instaLooter post <post_token> <directory> [options]
    instaLooter (-h | --help | --version | --usage)

 instaLooter post BZXkRHqDOF tes -D
Usage:
    instaLooter <profile> [<directory>] [options]
    instaLooter hashtag <hashtag> <directory> [options]
    instaLooter post <post_token> <directory> [options]
    instaLooter (-h | --help | --version | --usage)

**Comment by althonos** [comment]
The help message shows me that you are not using the latest version. Please update (`pip install --user -U instaLooter`). I tried with the latest version and it worked (but be careful, the post code in your command lacks an **8** at the end).
