### ISSUE TITLE
stories 

### ISSUE THREAD

**Issue by jali316** [althonos/InstaLooter#103]
Hello there
I am going to download just .txt not pictures /videos I use: 
`instaloader --login YOUR-USERNAME --password YOUR-PASSWORD -s PROFILE`
but this command download pictures too.
I add `--stories-only` instead of `--stories` it's not work like `--stories` when I add.
I need to download txt and skip to download pictures /videos
Thanks

**Comment by althonos** [comment]
You're not using my program, you're using [`instaloader`](https://github.com/Thammus/instaloader).

**Comment by jali316** [comment]
I use both ,but in this post I made a mistake ,Thanks for mention
