### ISSUE TITLE
Hashtag option not working? 

### ISSUE THREAD

**Issue by clityaw** [althonos/InstaLooter#109]
I'm trying to download pictures with the hashtag but whenever I try it displays the following outcome: 
```
python3 -m instaLooter hashtag python
Usage:
    instaLooter (login | logout)
    instaLooter batch <batch_file>
    instaLooter <profile> [<directory>] [options]
    instaLooter (hashtag <hashtag> | post <post_token>) <directory> [options]
    instaLooter (-h | --help | --version | --usage)
```
Someone help me please!!

**Comment by althonos** [comment]
You have to provide a directory explictly when downloading a hashtag, or else there could be a collision with other options. `python3 -m instaLooter hashtag python .` will work.
