### ISSUE TITLE
[Bug] AttributeError enter

### ISSUE THREAD

**Issue by yuktivhr** [althonos/InstaLooter#110]
I'm using instaLooter for the first time and running into following issue
\AppData\Local\Continuum\anaconda\lib\site-packages\instaLooter\core.py in pages(self, media_count, with_pbar)
    273         while True:
    274             current_page += 1
--> 275             with self.session.get(url) as res:
    276                 data = self._get_shared_data(res)
    277 

AttributeError: __enter__

Code is:
IL = InstaLooter(directory=outDir,template='{username}.{code}')
df['imgCode'].apply(IL.download_post)

**Comment by althonos** [comment]
@yuktivhr : this looks like an issue with an old version of Python. What is the version you're using ?

**Comment by althonos** [comment]
@yuktivhr : this is caused by and outdated `requests` install. Fixed since `v1` as the minimal pinned `requests` version does implement the context protocol for response objects.
