### ISSUE TITLE
API documentation is missing

### ISSUE THREAD

**Issue by nikifot** [althonos/InstaLooter#118]
Or at least I cannot find it! http://instalooter.readthedocs.io/en/latest/api.html
Does anyone have a version of it anywhere? an older one will work as well

**Comment by althonos** [comment]
I don't know why autodoc is not generating it, I'll try to fix that.
In the meantime, you can clone the project, and build the documentation yourself, using `sphinx`.

**Comment by althonos** [comment]
I don't know why autodoc is not generating it, I'll try to fix that.
I generated a html version with the latest version you can browse locally:
[apidoc.tar.gz](https://github.com/althonos/InstaLooter/files/1518435/apidoc.tar.gz)

**Comment by nikifot** [comment]
thanks :)

**Comment by althonos** [comment]
API reference is back online: http://instalooter.readthedocs.io/en/latest/api.html
