### ISSUE TITLE
[Feature Request] Return number of fans on the .get_owner_info()

### ISSUE THREAD

**Issue by nikifot** [althonos/InstaLooter#119]
it would be extremely useful to compare scale of accounts

**Comment by althonos** [comment]
Hi @nikifot,
currently you can access to this information with the following code (but I agree it would be easier to have it in the `get_owner_info` method:

```python
looter = instaLooter.InstaLooter()
code = "mypostcode"
owner_metadata = instaLooter.get_owner_info(code)

looter2 = instaLooter.InstaLooter(profile=owner_metadata['username'])
extended_metadata = looter2.get_metadata()

print("Account {meta['username']} is followed by {meta['followed_by']} persons".format(meta=extended_metadata)  
```

**Comment by nikifot** [comment]
thanks a lot for coming back to me! I did try a couple of options, but did not figure out how to get this!

**Comment by namanyayg** [comment]
How can this be done in the latest version?
