### ISSUE TITLE
Search by hashtag and save only post urls?

### ISSUE THREAD

**Issue by mrgloom** [althonos/InstaLooter#128]
Is it possible to search by hashtag and save only post urls(or save post as html)?

**Comment by althonos** [comment]
Basically, `instaLooter` gives you an iterator over the posts tagged with a hashtag, including the code of those posts (which you can build a post URL from).

Here's an example script that'll search for posts tagged with `Python` and save a list of post URLs in `urls.txt`:

```python
#!/usr/bin/env python

from instaLooter import InstaLooter
looter = InstaLooter(hashtag="Python")

with open('urls.txt', 'w') as f:
    for post in looter.medias():
        f.write("https://www.instagram.com/p/{}/\n".format(post['code']))
```

Please refer to the [API reference](http://instalooter.readthedocs.io/en/latest/api.html) to see how to give additional parameters to the `InstaLooter` constructor.
