### ISSUE TITLE
Installed command has not the right case

### ISSUE THREAD

**Issue by CuthbertCai** [althonos/InstaLooter#13]
seems like the command line should be 'instalooter' rather than 'instaLooter'

**Comment by althonos** [comment]
Well, the python module is called instaLooter so it is more consistent to call the CLI instaLooter as well

**Comment by CuthbertCai** [comment]
sorry about my bad expression, I mean that I meet a problem when I use this module.
According to the README.rst, the input should be 'instaLooter username directory [options]' in the Terminal.However, after I input the command, I got the message:'command not found:instaLooter'. While if I input:'instalooter username directory [options]', the module would work well. In addition, my linux distribution is Ubuntu 14.04.

**Comment by althonos** [comment]
Oh ! Okay I'm sorry, I thought you requested a name change.

It's strange though, I wrote the `setup.py` to register a command called `instaLooter`, not `instalooter`... Weird !

Are you using the latest version ?

**Comment by CuthbertCai** [comment]
I uninstall the package and install it with pip again.This bug seems be solved.I don't know why.Maybe I didn't use the latest version at the first time.

**Comment by althonos** [comment]
Weird, glad it works as intended now.
