### ISSUE TITLE
Hashtag json structure change

### ISSUE THREAD

**Issue by gffde3** [althonos/InstaLooter#130]
Looks like instagram has changed the way they handle hashtags now which makes the structure in the json document different to that of a profile.

- Profile json structure remains the same.
- Hashtag json structure updated with graphql returns.

This breaks the codebase as the functions in core.py handle these two data structures identically. 

Two fixes off the top of my head:
- mashing the json data from a hashtag data type in the pages function into the expected structure for the rest of the program
- splitting the core.py into functionality that deals with profile data structures or functionality for hashtag data structures

If I get time over the weekend (no promises, social life is in the way) I'll see if I can do a pull request and fix it using one of the two methods because I'm currently using this repo and I like it.

**Comment by hannahdonovan** [comment]
Yep, I'm having the same issue!

**Comment by gffde3** [comment]
I opted for fix 1 and restructured hashtag posts so they can be processed by the rest of the program without issue (avoids having to do alot more for now).

The pull request is here https://github.com/althonos/InstaLooter/pull/134 although Travis is having issues connecting to instagram so it randomly fails test cases due to connection issues. We'll see what the owner wants to do about it.

As an aside:

There is some funny business with timezones in unit tests.

I'm at GMT +10 so when I run the unit tests locally test_issue_41 fails to find "1467639884243493431.mp4" when timeframe=(datetime.date(2017, 3, 10) but finds it when I add a day and set it to timeframe=(datetime.date(2017, 3, 11)

Same goes for test_issue_12

It's definitely because I'm from the future.

**Comment by gaborpapp** [comment]
Encountered the same problem. #134 fixed it. Thanks!

**Comment by althonos** [comment]
Merged in `v0.14.0`. Thanks again @gffde3 !
