### ISSUE TITLE
If the hashtag function is out of date now?

### ISSUE THREAD

**Issue by dunning1** [althonos/InstaLooter#136]
Well, thank you for this useful tool...honestly.

However, I encounter the same message when using the hashtag download:

python -m instaLooter hashtag boys d:\instaPhoto -n 20 -u xxxx -p xxxx
10:20:16 - WARNING - Could not find page of user: boys
10:20:16 - WARNING - No medias found.

Obviously, I have read all the previous issues mentioning this problem, and make sure that a credentials and a directory were added. If the hashtag function is out of date now? Many thanks for reply :)

**Comment by gffde3** [comment]
Hey, it's probably the same issue as here: https://github.com/althonos/InstaLooter/issues/130

Basically it looks like instagram changed the data structure for tag based posts (profiles / tags were originally treated the same); so the code throws an exception when it looks up a key in a dictionary that doesn't exist. It'll get fixed eventually (there is a fix in the other issue; but it may require some checks / QA)

**Comment by althonos** [comment]
This will be fixed in `v0.14.0`.

**Comment by dunning1** [comment]
Well, I've updated the latest version, it works well, exciting...
