### ISSUE TITLE
[Feature request] Allow customizing filenames of downloaded files

### ISSUE THREAD

**Issue by JFLarsen** [althonos/InstaLooter#14]
Great program, works as intended, but i have some feature suggestions.

1. Integrate Instagram username into filename.
2. The original upload date  is displayed on Instagram. Is there a way to put that date into the images EXIF data? That makes it possible to sort the images on the date it was "taken" (uploaded)

Reg.
JFLarsen

**Comment by althonos** [comment]
Hi JFLarsen, thanks for feedback :)
If using the `--add-metadata` option, the upload date will be added to the exif (using the online Instagram date timestamp).

For the name, i'll start thinking of a nice way to customize the filenames, stay tuned !

**Comment by althonos** [comment]
Feature is out, here's the gist of it:
use the `-T` flag to give a template, using Python default template system (`{value}`) with the following available variables: `ownerid`, `username`, `fullname`, `id`, `code`, `date`, `datetime`, `width`, `height`, `likescount`, `commentscount`.

So for instance:
```
instaLooter profile dir -T {date}.{username}.{id}
instaLooter profile dir -T {date}.{username}.{id}
instaLooter profile dir -T anything_constant.{code}
instaLooter profile dir -T {width}x{height}.{likescount}.{id}
```

Just take care to use a unique identifier (either `id`, `code` or `datetime`) somewhere to avoid name collision.

**Comment by althonos** [comment]
Please comment if you have trouble with this feature, and I'll reopen the issue.

**Comment by paramjitrohit** [comment]
Do you know of a way to batch rename already downloaded images? I mean, renaming from the EXIF tagdata.

**Comment by frozenpandaman** [comment]
@althonos Is there any variable or way to keep the original filename, i.e. the `12345_12345_12345_n.jpg`-like naming structure?

**Comment by frozenpandaman** [comment]
Nevermind :)
