### ISSUE TITLE
Display batch mode progress

### ISSUE THREAD

**Issue by douglasrizzo** [althonos/InstaLooter#140]
When I use instaLooter in batch mode, there is no output displaying which profile is currently being downloaded or a `current/total` profiles/hashtags count. While this kind of output is not necessary, it would be useful, since batch mode can take a long time and you can lose count of how many profiles/hashtags have been processed if you don't look at the terminal during the download process.

**Comment by althonos** [comment]
`v2.1.0` will now display the current section as well as the current profile / hashtag being downloaded, unless the logging level is higher than `INFO`.
