### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by JonasGrobe** [althonos/InstaLooter#148]
I still get the new posts, but if i download them the file just contains "Access Denied".
InstaLooter shows no error or warning.
It happens on private and public accounts.

**Comment by JonasGrobe** [comment]
I tried it on windows, on linux as normal user and on linux as sudo...
It's not a problem with os-rights - the problem is Instagram sending back "Access denied" instead of the actual image data

**Comment by polyzen** [comment]
Related to https://github.com/rarcega/instagram-scraper/issues/193.

**Comment by althonos** [comment]
What version are you using ? What Python version ? What command ? If you're not using it, you should use the new alpha version (`v1.0.0-a.1`).

**Comment by JonasGrobe** [comment]
I'm using python 3.6.2 and just switched to the alpha, which led to another problem... 

> looter = instalooter.InstaLooter("./files/" + pair[1] + "/posts/", profile=pair[1], get_videos=True)
AttributeError: module 'instalooter' has no attribute 'InstaLooter'

So I changed the imports to 
```
import instalooter
from instalooter.looters import *
```
and got the error message

> looter = instalooter.looters.InstaLooter("./files/" + pair[1] + "/posts/", profile=pair[1], get_videos=True)
> TypeError: Can't instantiate abstract class InstaLooter with abstract methods pages

**Comment by althonos** [comment]
@JonasGrobe : since I reimplemented the whole library, I changed the API as well. `InstaLooter` is now an abstract class, use one of its subclasses to download what you want:

* `ProfileLooter` to fetch medias from a profile page
* `HashtagLooter` to search for medias tagged with a hashtag
* `PostLooter` to get a single post

The `target` directory is now passed as the main `download` argument, so you should end up with something like:
```python
from instalooter.looters import ProfileLooter
looter = ProfileLooter(pair[1], get_videos=True)
looter.download("./files/"+pair[1]+"/posts/")
```

**Comment by JonasGrobe** [comment]
@althonos Ok, now it tells me
> looters.py", line 122, in _login
>     raise ValueError('Login error: check your login data')

But without logging in downloading from public accounts works now. Good job!

**Comment by althonos** [comment]
@JonasGrobe : Great. I'll be closing this issue in favour of #150. Don't hesitate to open a ticket if you discover other bugs.
