### ISSUE TITLE
Login does not work with `v1.0`

### ISSUE THREAD

**Issue by althonos** [althonos/InstaLooter#150]
With API changes it seem the old method used to login with the internal HTTP session does not work anymore.

**Comment by WenxuanZhang** [comment]
Wish I can understand the source code and fix the issue

**Comment by AbysmalBiscuit** [comment]
@althonos I'll have a look into this and try to fix it. :)

**Comment by AbysmalBiscuit** [comment]
I've gotten logging in to work, I just need to iron out a few kinks and then I'll submit a PR.

**Comment by AbysmalBiscuit** [comment]
For people that would like to test to see if my fix works, please see my PR #153.

**Comment by althonos** [comment]
Fixed in `v1.0.0-a.2` (install with `--pre` flag, it's a pre-release for now).

**Comment by muglikar** [comment]
Still does not work.
