### ISSUE TITLE
Can't install 1.0

### ISSUE THREAD

**Issue by dmarkdk** [althonos/InstaLooter#152]
I am feeling like a complete newbie. I can't figure out how to install the new alpha. I tried

pip install https://github.com/althonos/InstaLooter/archive/v1.0.0-a.1.zip

I tried downloading https://github.com/althonos/InstaLooter/archive/master.zip, unzipping it and then run
python setup.py install

The output is:

running install
running bdist_egg
running egg_info
creating UNKNOWN.egg-info
writing UNKNOWN.egg-info/PKG-INFO
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying UNKNOWN.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/UNKNOWN-0.0.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing UNKNOWN-0.0.0-py2.7.egg
Removing /usr/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg
Copying UNKNOWN-0.0.0-py2.7.egg to /usr/lib/python2.7/site-packages
UNKNOWN 0.0.0 is already the active version in easy-install.pth

Installed /usr/lib/python2.7/site-packages/UNKNOWN-0.0.0-py2.7.egg
Processing dependencies for UNKNOWN==0.0.0
Finished processing dependencies for UNKNOWN==0.0.0

I can't find any binary anywhere, and there's not instaLooter in /usr/lib64/python3.4/site-packages/ (with the old 0.14, it sits here and works perfectly. I am on CentOS 7 and Python 3.4.

It is probably something very basic that I just don't get, but can you please help out?

**Comment by althonos** [comment]
You're missing an up-to-date `setuptools` package: try 
```
pip install instalooter --pre
```
it should download the package from PyPI instead, and hopefully use enforce the update of the library.

If not, then run
```
pip install -U setuptools
```

**Comment by dmarkdk** [comment]
It works now, thank you!

**Comment by althonos** [comment]
Great !
