### ISSUE TITLE
Add requirement for Python 3.5.2  (typing has not attribute TYPE_CHECKING)

### ISSUE THREAD

**Issue by marekpola** [althonos/InstaLooter#155]
## Version
installoter 1.0.0-a.3
## Environment
* macOS 10.13.3
* *Python version* 3.5.1 |Anaconda custom (x86_64)| (default, Jun 15 2016, 16:14:02) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)]
## Error description
```
AttributeError                            Traceback (most recent call last)
<ipython-input-7-9dcea390655e> in <module>()
----> 1 import instalooter.looters

/Users/marek/.local/lib/python3.5/site-packages/instalooter/looters.py in <module>()
     22 from . import __author__, __name__ as __appname__, __version__
     23 from ._impl import length_hint
---> 24 from ._utils import NameGenerator, CachedClassProperty
     25 from .medias import TimedMediasIterator, MediasIterator
     26 from .pages import ProfileIterator, HashtagIterator

/Users/marek/.local/lib/python3.5/site-packages/instalooter/_utils.py in <module>()
     12 import six
     13 
---> 14 if typing.TYPE_CHECKING:
     15     from typing import Any, Dict, Mapping, Optional, Text
     16 

AttributeError: module 'typing' has no attribute 'TYPE_CHECKING'
```
*If you have an issue at runtime, include the required information below:*

### Reproducible test case

```python
from instalooter.looters import ProfileLooter
```

### Details
typing has version 
typing==3.6.4

## Solution
solved by update to version 3.5.4

please add python version 3.5.2 to requirements  - attribute TYPE_CHECKING has been added to 3.5.2 (and is not present in earlier versions)

**Comment by althonos** [comment]
Fixed, thanks. I made sure Python `3.5.1` is not in the `python_requires` configuration, so that users on `3.5.1` should see a setuptools complaint when trying to install. Will be in the next release.
