### ISSUE TITLE
Using --quiet in CLI doesn't print (stderr/stdout) private profiles

### ISSUE THREAD

**Issue by raphaelbernardino** [althonos/InstaLooter#156]
## Library version
`instalooter --version`: instalooter 1.0.0-a.3

## Environment
* *OS*: Linux Ubuntu 16.04
* *Python version*: 3.5.2

### Reproducible test case

```
instalooter user raphaelbernardino --quiet
```

### Expected behaviour

Print user `raphaelbernardino` is private.

**Comment by althonos** [comment]
The actual error is that the CLI was missing an error for private users. The `--quiet` flag only hides non-critical output, which is what we want.

Since `v1.0.0-a.4`, calling `instalooter user` on a private user will raise an error, which will be displayed even with the `--quiet` flag.
