### ISSUE TITLE
'no medias found' on all accounts

### ISSUE THREAD

**Issue by belle-et-bonne** [althonos/InstaLooter#165]
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

```
instalooter v2.0.0
```

## Environment

*Describe here your environment, including:*

Windows 8
Python 3.6.1

## Error description - runtime

*If you have an issue at runtime, include the required information below:*

I get a "no medias found" error when downloading public accounts.

### Reproducible test case

*Are you using the CLI ? If so, include a command that can be used to re-raise the 
error, with actual arguments anybody can try:*

```
instalooter user theashleygraham
```

### Expected behaviour

*What's supposed to happen ? That's were you can ask for a new feature as well*

All the photos from Ashley Graham's account are supposed to download into the current directory.

### Actual behaviour

*What's actually happening ? Leave empty if asking for a new feature*

C:\Users\V3-572G\Desktop\example instalooter downloads>instalooter user theashleygraham
2018-04-17 22:19:19 V3-572G-PC instalooter.cli[13260] NOTICE Starting download of `theashleygraham`
0it [00:00, ?it/s]
2018-04-17 22:19:20 V3-572G-PC instalooter.cli

[13260] WARNING No medias found.

C:\Users\V3-572G\Desktop\example instalooter downloads>

![image](https://user-images.githubusercontent.com/38482397/38908324-a85279e0-428d-11e8-80eb-5a8bcbc3a75b.png)

**Comment by althonos** [comment]
Fixed in `v2.0.1`. IG changed its internal API once again, I had to tweak a few things.
