### ISSUE TITLE
Rate limiting from Instagram?

### ISSUE THREAD

**Issue by wrybread** [althonos/InstaLooter#175]
I'm using InstaLooter to detect when new photos are added for a given tag, so just doing a search over and over. The problem is that Instagram disables the account after about 200 searches in a row. 

I don't imaging anyone knows a way around this limitation from Instagram?

**Comment by althonos** [comment]
I don't even know what the actual rate limits *are* at the moment, so not really. You could try rewriting some parts of the library to avoid using GraphQL queries (which is what I did pre-v1, but it's a lot messier to work with) since "normal" HTTP queries to actual pages seem not to be limited.

**Comment by wrybread** [comment]
Does anyone else know what the limits might be? I keep getting "CRITICAL Query rate exceeded (wait before next run)".  Previously I could get around that by logging in as a different user, but no more. I updated to the latest version, I wonder if that changed it?

**Comment by distantstar** [comment]
I think it's around 15-20 minutes.

**Comment by 0xNF** [comment]
Sorry for posting into an old, closed thread, but recent research suggests that it's closer to 30 minutes, as of November 7th, 2018, and caps after 20 graphql page requests.
