### ISSUE TITLE
CLI API crash on non existing user name

### ISSUE THREAD

**Issue by mrgloom** [althonos/InstaLooter#18]
When I try to run app via CLI inteface with username that is not exist it gives me an error:

~~~
Traceback (most recent call last):
  File "/usr/local/bin/instaLooter", line 9, in <module>
    load_entry_point('instaLooter==0.4.0', 'console_scripts', 'instaLooter')()
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/__main__.py", line 82, in main
    new_only=args['--new'],
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/core.py", line 355, in download
    new_only=new_only)
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/core.py", line 401, in _fill_media_queue
    for media in self.medias(media_count=media_count, with_pbar=with_pbar, timeframe=timeframe):
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/core.py", line 246, in _timeless_medias
    for page in self.pages(media_count=media_count, with_pbar=with_pbar):
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/core.py", line 200, in pages
    media_count = data['entry_data'][self._page_name][0][self._section_name]['media']['count']
KeyError: u'ProfilePage'
~~~

maybe better way is to print warning?

p.s. Users frequently change their names, but I guess their internal ID remains unchanged, is there any way to match user names and user ID and get new user name by ID?

**Comment by althonos** [comment]
Yes, I'll add a pretty error message based on this.

The name in the url is always the same I guess, and it's the one instaLooter uses, so no big deal if the "full_name" changes. If not then I don't know if there's a way to link a user ID to a username without using the official API.

**Comment by mrgloom** [comment]
As far as I know user can change name (all content of account remains the same, so it's not account recreation).

Also when account is private app via CLI API gives no warning\error, I think this also should be reported somehow (by warning?) because account can become private at any time(for example at second time when your want to download fresh portion of photos).

**Comment by althonos** [comment]
A warning is now issues when:
- the user was not found
- no medias were found

You can use python builtin `-W` flag to turn those into errors, and I'll add a flag for the CLI to do the exact same thing.

**Comment by mrgloom** [comment]
Also crash when `This Account is Private` using CLI API.

```
instaLooter --version
instaLooter 0.4.0
```

Was it fixed? Or maybe I can overcome it via python API?

**Comment by althonos** [comment]
So, I added a `-W` parameter to the CLI, that can be used to transform a warning into an error. I also fixed the CLI so that when the program exits with an error, the return code is 1.

@mrgloom : try updating, the current version is `0.9.0` and I've done some more stability fixes. If this keeps happening then please open another issue, I'll be closing this one.
