### ISSUE TITLE
[deps/pgks] Required package 'coloredlogs' on new major version

### ISSUE THREAD

**Issue by Hrxn** [althonos/InstaLooter#183]
## Library version

```
instalooter 2.0.1
```

## Environment

* Windows 10 x64 v1803
* Python v3.6.5 x64

## Issue description
Instalooter lists this as version range..
https://github.com/althonos/InstaLooter/blob/ac74fc3c1b6294690b8007c6e5ad16977c7b2a3b/setup.cfg#L28-L35

`coloredlogs ~=9.0`

But [coloredlogs](https://github.com/xolox/python-coloredlogs) has been updated to version `10.0` (3 days ago), this is the official release version distributed via PyPI..

Making `pip` complain.. 😟 
```
PS C:\Users\Hrxn> pip check --verbose
instalooter 2.0.1 has requirement coloredlogs~=9.0, but you have coloredlogs 10.0.
PS C:\Users\Hrxn>
```

**Comment by althonos** [comment]
Bumped dependency in latest release (`v2.0.2`), thanks !
