### ISSUE TITLE
CSRF token issues

### ISSUE THREAD

**Issue by andybobby** [althonos/InstaLooter#192]
re: instalooter latest pip install

Environment

Win 7
Python 3.6

Error description - runtime

Reproducible test case

python -m instalooter user instagram

Expected behaviour

Approx a week ago this command would download images for the user

Actual behaviour

Responds with: "name=u'csrftoken', domain=None, path=None"

**Comment by Paradoxis** [comment]
Same issue here, running under Ubuntu 16.04.03, virtualenv:

```
appdirs==1.4.3
certifi==2018.4.16
chardet==3.0.4
coloredlogs==10.0
docopt==0.6.2
fake-useragent==0.1.10
fs==2.0.23
humanfriendly==4.12.1
idna==2.6
instalooter==2.0.2
python-dateutil==2.7.3
pytz==2018.4
requests==2.18.4
six==1.11.0
tenacity==4.12.0
tqdm==4.23.4
typing==3.6.4
urllib3==1.22
verboselogs==1.7
```

**Comment by althonos** [comment]
Indeed, thanks. I'll try to merge the upstream patch.
