### ISSUE TITLE
Batch mode exits on private profile.

### ISSUE THREAD

**Issue by timwilson402** [althonos/InstaLooter#196]
## Error description - runtime

When using Instalooter in batch mode,  it will exit when hitting a private profile.

### Expected behaviour

Expect for Instalooter to skip to next profile when hitting private profile.

**Comment by polyzen** [comment]
Related to #185.

**Comment by althonos** [comment]
Resolved in abce96d72eb32d52eb46b309f49bd441af70ef06.
