### ISSUE TITLE
Not Downloading Metadata (Batch Mode)

### ISSUE THREAD

**Issue by ChrisBuetti** [althonos/InstaLooter#197]
When I try to download pictures and metadata, I am only getting pictures. Here is what my .ini file looks like:

```
[Test]
num-to-dl = 3
dump-json = True
users =
    brunomars: /path/to/dir
    therock: /path/to/dir
```

When I run `instalooter batch /path/to/file/test.ini` from the CLI, it only downloads the six images and no associated metadata jsons.

However, when I want to download only metadata and no images, I am correctly downloading the jsons (like follows:)

```
[Test]
num-to-dl = 3
dump-only= True
users =
    brunomars: /path/to/dir
    therock: /path/to/dir
```

I appreciate any help. Thanks.

**Comment by polyzen** [comment]
The actual parameter is `dump-json`.

**Comment by ChrisBuetti** [comment]
@polyzen apologize for the typo, but that didn't solve my problem. Editing and correcting that typo, do you see any other issue? 

Thanks!

**Comment by polyzen** [comment]
Oh no. Have you tried `dump-json` outside of batch mode?

**Comment by ChrisBuetti** [comment]
@polyzen I got it to work, I think I just had some formatting errors inside my .ini file. Sorry about that.
