### ISSUE TITLE
[Bug] --new / -N no longer working?

### ISSUE THREAD

**Issue by SmokE-PGF** [althonos/InstaLooter#20]
# instalooter --version
instaLooter 0.4.0

There doesn't seem to be an option to grab just the new files anymore -N and --new results in instalooter showing usage.

**Comment by althonos** [comment]
Didn't work for me at some point, but after fresh install it started working back again. Dunno if that would work for you too though (_have you tried turning it off and on again ?_) :smile:

**Comment by SmokE-PGF** [comment]
haha I will try and get back to you but that was a fresh install

**Comment by SmokE-PGF** [comment]
Not working however the filename did change from instalooter to instaLooter lol
