### ISSUE TITLE
Only the first photo is downloaded from multiple photos post

### ISSUE THREAD

**Issue by k3rn** [althonos/InstaLooter#201]
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

```
instalooter v2.0.3
```

## Environment

*Describe here your environment, including:*

* *macOS 10.12.6*
* *Python 3.6.4*

### Reproducible test case

```
instalooter post Bj94d5gA33P .
```

### Expected behaviour

*Download all the photos from post*

### Actual behaviour

*Only the first photo is downloaded*

**Comment by althonos** [comment]
Is this still occurring ? When trying your test case I downloaded 4 files as expected.

**Comment by k3rn** [comment]
Tested and this is not occurring anymore.
