### ISSUE TITLE
Renaming every pictures with the user ID ?

### ISSUE THREAD

**Issue by Miserness974** [althonos/InstaLooter#204]
Hello,

I have a question about your awesome code. I want to take all the pictures from a hashtag and rename it with the name of the user that post it. Is it possible to do it the simple way ?
I know how to take every pictures on Python but, I don't know how to take the username and directly rename the picture.

I hope you can help me ;) 

Thx,
Lazare

**Comment by althonos** [comment]
Hi Lazare,
you can simply use the `-T` / `--template` flag with the CLI, or the `template` keyword argument when instantiating a looter within the code. For instance:
```console
$ instalooter hashtag python /tmp -m -n5 -T "{username}.{id}"
```
will create the following files:
```text
 anthonyratpack.1808357717828437887.jpg
 boycoding.1808359780562468223.jpg
 grayhacker.1808360660854488678.jpg
 j.leon_mc.1808359414551629269.jpg
 komunitas_reptile_lamongan.1808358367828134735.jpg
```

Hopefully that's what you want.

**Comment by althonos** [comment]
See http://instalooter.readthedocs.io/en/latest/usage.html#template for additional information.

**Comment by Miserness974** [comment]
How do I integrate that in Python ? Cause I have seen that on the docs but I don't know how to put this in. 

Thx for your answer, I appreciate it.

**Comment by althonos** [comment]
You have to create a hashtag looter with that template, and then download normally:
```python
from instalooter.looters import HashtagLooter

looter = HashtagLooter('awesome_hashtag', template="{username}.{id}")
looter.download('/output/path')
```

That's only an example, you may want to tweak parameters here.

**Comment by Miserness974** [comment]
Thank you ! Is it possible to get pictures from a special country ?

Best regards,
Lazare
