### ISSUE TITLE
Batch mode fails to download when user contains a dot "."

### ISSUE THREAD

**Issue by BobMacpherson** [althonos/InstaLooter#210]
## Library version
2.0.3

## Environment
Archlinux
Python 3.6.6

## Error description - runtime
When using batch mode, a profile that has dot "." in it errors out and dumps to stdout before quitting.
Example "user.user2"
### Reproducible test case
insta.ini
[insta]
	username = username
	password = password
	add-metadata = true
	extended-dump = true
	get-videos = true
	new = true
users =
	user.user2: /path/to/folder/user.user2
Executed with:
instalooter batch /path/to/insta.ini

### Expected behaviour
That profile "user.user2" should be downloaded using batch mode in to "user.user2" folder in path.

### Actual behaviour
Instalooter errors out with
"instalooter.cli[18272] CRITICAL 'ProfilePage'/s]"

However running instalooter in the cli with
instalooter -u user -p password -Nmve user user.user2 /path/to/save/point/user.user2
Properly saves the user "user.user2" to "user.user2" folder in given path.

**Comment by althonos** [comment]
@BobMacpherson : Is it still occurring ? I just tested with `elle.mills` and it seemed to work.
