### ISSUE TITLE
No module named Instalooter

### ISSUE THREAD

**Issue by Amazingduf** [althonos/InstaLooter#215]
*What's the installed library version ?

instalooter v2.3.0

## Environment

OS
Windows 8.1 pro

* *Python version*
3.7.0

## Error description - installation

I just installed the app and I tried multiple command to try it out but nothing is working, every time it tells me:
"C:\Users\****\AppData\Local\Programs\Python\Python37\python.exe: No module named instaLooter"

what am I doing wrong ?

Instalooter is not add to PATH so it only attempts to work with "python -m instaLooter "

**Comment by rizkiyoist** [comment]
Check if instalooter.py is inside your scripts folder inside AppData\Roaming.
Something like C:\Users\yourusername\AppData\Roaming\Python\Python35\Scripts

**Comment by rizkiyoist** [comment]
My bad, I really meant instalooter.exe not py.

**Comment by Amazingduf** [comment]
It works now, I just tried it again and it works, I just used the simple `python -m instaLooter` command, I don't know why it didn't work before, thank you tho,
