### ISSUE TITLE
What is the function format for condition parameter?

### ISSUE THREAD

**Issue by yudataguy** [althonos/InstaLooter#257]
Mac, Python 3.7.4, ProfileLooter

What is supposed to be the format of condition parameter function? 

I've tried string, boolean, and function 
```
def get_video():
    return 'get_videos'
```
Read the source code, but still unclear on the format for the condition function. 

but none worked, what is supposed to be the right format, so I can looter both video and photo with ProfileLooter?

**Comment by althonos** [comment]
The signature for `condition` is `Optional[Callable[[dict], bool]]`: it is either a callable that takes a 
`dict` and returns a `bool`, or `None`. The `dict` is the same you would get while iterating over the medias of a looter with the `InstaLooter.medias` method.

**Comment by yudataguy** [comment]
Sorry I'm not understanding this. Can I write a callback function like 
```lambda media: is media["is_video"]```  to return all the photos and videos?

**Comment by althonos** [comment]
`lambda media: True` will download everything.
