### ISSUE TITLE
Instalooter is freezing and not doing anything 

### ISSUE THREAD

**Issue by mhkarimi** [althonos/InstaLooter#258]
## Library version

```
 instalooter 2.4.0
```

## Environment

* *OS ubuntu 18.05*
* *Python version 2.7*

## Error description - runtime
instalooter is not working and actually is not giving any reaction. it kind of freezing and even --traceback and --loglevel is not printing any thing. it just freezes and I have to kill the process to stop it.  
I also uninstalled and installed it again and again both with pip install instalooter and also from the github source code
Could any body help me out here? thanks

**Comment by althonos** [comment]
Maybe related to #254. Try creating the user-agent file as described in that issue.

**Comment by mhkarimi** [comment]
Thank you, Exactly
