### ISSUE TITLE
Doesn't download videos in user-mode

### ISSUE THREAD

**Issue by chrissxYT** [althonos/InstaLooter#259]
## Library version

```
instalooter v2.4.0
```

## Environment

* Ubuntu Linux 19.04 (i3buntu)
* 2.7.16

### Reproducible test case

*Are you using the CLI ? If so, include a command that can be used to re-raise the
error, with actual arguments anybody can try:*

```
instalooter user sly.sc
```

### Expected behaviour

It downloads all the photos and videos.

### Actual behaviour

It downloads only the photos and not the videos.

**Comment by Henning-K** [comment]
I thought downloading videos requires the option "--get-videos" since instalooter only get pictures by default.

**Comment by chrissxYT** [comment]
So it is just the result of an unusual default.

**Comment by Henning-K** [comment]
> So it is just the result of an unusual default.

This is probably because videos are mostly vastly larger in size than images and to prevent unexpected filling up of hard drives and/or "looting" taking forever.

**Comment by chrissxYT** [comment]
> > So it is just the result of an unusual default.
> 
> This is probably because videos are mostly vastly larger in size than images and to prevent unexpected filling up of hard drives and/or "looting" taking forever.

I still think, this shouldn't be the default, because it does actually not take a lot of space, good luck getting your Instagram larger than 1GB with videos. I expect a program downloading Instagram posts to by default download all the posts and a flag to turn videos or photos off.
