### ISSUE TITLE
[Feature request] Download the full resolution picture

### ISSUE THREAD

**Issue by verafide** [althonos/InstaLooter#26]
At times some pictures will have something like this `/p480x480` in the direct URL so when InstaLooter downloads the picture it's at a slightly lower resolution than it could be. Here is an example  
* [Original direct URL](https://scontent.cdninstagram.com/t51.2885-15/e35/p480x480/15876204_370847143275022_6186941535674695680_n.jpg)  
* [/p480x480 removed](https://scontent.cdninstagram.com/t51.2885-15/e35/15876204_370847143275022_6186941535674695680_n.jpg)  
* [Source of the Picture](https://www.instagram.com/p/BO0XpEshejh/)  

Although it's not always the same number, it is as far as I've seen always in the same location of the URL which is after the `/e35` and before `/15876204_370847143275022_6186941535674695680_n.jpg`

I know the difference in resolution here is very minor but at times it's a bit more extreme. I'm hoping InstaLooter can possibly be made to detect and remove when something like `/p480x480` is present. I'd appreciate any responses

**Comment by althonos** [comment]
Hi there, thanks for feedback about this issue. Since Instagram returns a JSON which key is display_src, I did not know if there was a higher res version available.

It would be very easy to detect and remove the resizing, something along the lines of a regex
```python
url = re.sub('(/p[0-9]*x[0-9]*)', '', url)
```
and we would be done here. I'll try to implement that today or tomorrow.

**Comment by althonos** [comment]
Implemented in 4419f6f1fa78d2ec4d06f02ee24238aa844c48a4. (Now that's what you call agile development 🖥 🔨)
