### ISSUE TITLE
template in batch mode not working(screenshot included)

### ISSUE THREAD

**Issue by beakwood** [althonos/InstaLooter#270]
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

```
instalooter v2.4.0
```

## Environment

*Describe here your environment, including:*

Windows 10
Python 3.6.8

### Reproducible test case

*Are you using the CLI ? If so, include a command that can be used to re-raise the
error, with actual arguments anybody can try:*

```
instalooter batch D:\instaLooterDownloads\hkinginstalooterSMALL.ini
```

### Expected behaviour

*What's supposed to happen ? That's were you can ask for a new feature as well*
The filename should change like it does using the CLI only without using batch. For example, 
instalooter user username -T {username}.{datetime}
works perfectly fine. 

### Actual behaviour
The id of the file is only being used when running. I have attached a screenshot to show my configs

https://prnt.sc/pfg22o

**Comment by althonos** [comment]
You probably need to add all your configuration to the section you're extracting users from, not to a different section:
```ini
[Users]
username = ...
password = ...
new = true
template = {username.datetime}
jobs = 16
users = 
    playapex : D:instalooter\Downloads\playapex
````

**Comment by beakwood** [comment]
Oh wow. Such a simple mistake. Thank you for providing the solution. Thank you!
