### ISSUE TITLE
Download single image?

### ISSUE THREAD

**Issue by GraphicsComputing** [althonos/InstaLooter#28]
Is this possible? Instead of downloading *ALL* of "Instagram"'s images, i would like to save only one
For example:
https://www.instagram.com/p/BP0M7XZjMar/

Thanks.

**Comment by althonos** [comment]
You can do that if you use the Python API, using the [download_post](http://instalooter.readthedocs.io/en/latest/api.html#instaLooter.InstaLooter.download_post) fonction. Create a looter instance with an empty target but with a directory, and then use the download_post function giving the code of the post you wish to download.

I can provide you with a script to do that if you're not familiar with Python.

**Comment by GraphicsComputing** [comment]
That'd be awesome of you do provide me a script for that. Thanks

**Comment by althonos** [comment]
Try running the attached script with Python3, you provide it the url of the post you wish to download and an optional destination directory (else current directory is used) and it downloads the post in the current directory.

```python
#!/bin/env python3
import os
import re
import argparse
from instaLooter import InstaLooter

# Create the regex to extract the code of the post
RX_CODE_EXTRACTER = re.compile('/p/([^/]*)/')

# Create the command line interface
parser = argparse.ArgumentParser()
parser.add_argument('url', help="the url of the post")
parser.add_argument('--directory', default=os.getcwd(),
                    metavar='DIR', help="the directory "
                    "to download the post into [default: "
                    "current dir]")

# Parse the arguments
args = parser.parse_args()

# Create an InstaLooter instance in the given
# directory
looter = InstaLooter(args.directory)

# Extract the code from the url
regex_result = RX_CODE_EXTRACTER.search(args.url)
if regex_result is None:
    parser.error("invalid url: {}".format(args.url))
else:
    code = regex_result.group(1)

# Download the post
looter.download_post(code)
```

**Comment by GraphicsComputing** [comment]
Thanks for the help! 👍
