### ISSUE TITLE
How to download a video by simply giving the Video post URL ?

### ISSUE THREAD

**Issue by TechRova** [althonos/InstaLooter#281]
I want to download by giving a video post URL directly ? 

ex: https://www.instagram.com/p/B8uguWWH5aa/?igshid=6czbf87d7drh

is it possible ?

**Comment by althonos** [comment]
You can use the `post` subcommand, together with the `-v` flag to enable download of videos:
```console
$ instalooter post -v "https://www.instagram.com/p/B8uguWWH5aa/?igshid=6czbf87d7drh"
```
