### ISSUE TITLE
No output to terminal and no files download

### ISSUE THREAD

**Issue by atcapollo** [althonos/InstaLooter#286]
## Library version
```
instalooter 2.4.2
```

## Environment

* *OS* Ubuntu 16.04
* *Python version* 3.5.2

## Error description - installation
Command runs silently with no output. Runs for ages without exception or output. Quiet flag is not used.

## Error description - runtime
n/a

### Reproducible test case
```
instalooter user USERNAME '/DATA/Data/Photos/Instagram/' -u USERNAME -p PASSWORD -N -T {username}-{datetime}.{id}.{width}x{height}
```

### Expected behaviour
Output to terminal and files downloading

### Actual behaviour
No output to terminal and no files download

**Comment by atcapollo** [comment]
More debugging instalooter just seems to fail to login. 

`instalooter login`

Just sits there with no output after the password is entered.

**Comment by atcapollo** [comment]
Solved, the new version I installed on instalooter needed a reboot in order for the user agent to be set. 

A reboot of they system and the issue went away.

**Comment by abdoljabbar** [comment]
i have the same issue.
OS: ubuntu server
and reboot didn't fix that problem.
does anybody face this issue?

**Comment by oweingrod** [comment]
@abdoljabbar You likely need to add a user agent string to the directory `~/.cache/instalooter/<VERSION>/user-agent.txt`. When running on a machine w/ access to a browser, this is retrieved. On Ubuntu server, you need to add the user agent manually.

**Comment by aakashcurefit** [comment]
@abdoljabbar did this work for you? 

I am also facing the same issues during login on the ubuntu server. 

@takeout1 exactly what string do we have to add inside user-agent.txt?
