### ISSUE TITLE
API Call

### ISSUE THREAD

**Issue by RPSPandora** [althonos/InstaLooter#29]
hi, i want to call the instaLooter API on another python script.
can you give me an example?

```
from instaLooter import InstaLooter, __init__
hashtagDump = "hashtag here"
DownloadPath = "dump location"

InstaLooter(hastag hashtagDump, DownloadPath, -n 10, -T "@{username}---{id}")
```

give me 

```
InstaLooter(hastag hashtagDump, dump, -n 10, -T "@{username}---{id}")   
                                 ^
SyntaxError: invalid syntax
```

**Comment by althonos** [comment]
The easiest would be to use the following:
```python
from instaLooter import InstaLooter
looter = InstaLooter(directory="YOUR DOWNLOAD PATH",
                     hashtag="YOUR HASHTAG",
                     template="@{username}--{id}")
looter.download(media_count=10)
```

You can have a look at the [examples](http://instalooter.readthedocs.io/en/latest/examples.html) and at 
the [API reference](http://instalooter.readthedocs.io/en/latest/api.html) to see how it works in details.

**Comment by RPSPandora** [comment]
Ah i see, will try again later.

Thanks 👍 great work

On Feb 1, 2017 6:14 PM, "Martin Larralde" <notifications@github.com> wrote:

The easiest would be to use the following:

from instaLooter import InstaLooter
looter = InstaLooter(directory="YOUR DOWNLOAD PATH",
                     hashtag="YOUR HASHTAG",
                     template="@{username}--{id}")
looter.download(media_count=10)

You can have a look at the examples
<http://instalooter.readthedocs.io/en/latest/examples.html> and at
the API reference <http://instalooter.readthedocs.io/en/latest/api.html> to
see how it works in details.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/althonos/InstaLooter/issues/29#issuecomment-276632404>,
or mute the thread
