### ISSUE TITLE
Question: Download hashtag

### ISSUE THREAD

**Issue by fredericofs** [althonos/InstaLooter#3]
Hello, thanks for this great project.
Is it possible to modify it to download photos of a given hashtag?
Or better yet, just output the direct urls, usernames, like counts...

**Comment by althonos** [comment]
Thanks for feedback ! I'll check it, I don't know how hashtag pages are handled by IG.

If this is possible with the same method as I did for user pages, then it will be possible to extract metada and urls only, through Python. I'll write you a snippet if needed.

**Comment by althonos** [comment]
Turns out it is ! If you download the latest GitHub version, you'll be able to download photos of a given hashtag (look at CLI help to see how to.)

To get information for each picture of a hashtag, initialize an InstaLooter instance:
```python
import instaLooter
import tempfile

looter = instaLooter.InstaLooter(tempfile.mkdtemp(), hashtag="yourhashtag")
for media in looter.pages(with_pbar=False) # set to True if you want the progress bar to display
    ...
```

You'll be able to iterate on a metadata dictionary for each media structured like the following one:
```json
{
    "caption": "Ubuntu fan and you are? -\n-\n-\n#windows #ios #ubuntu #mint #win7 #win10 #win8 #ios9 #ios8 #linux \n#programmer #programming #coding #code #coder #computerscience #developer #codingquotes #tech #setup #php #python #html #css #java #javascript #webdev #coderlife #webdesign",
    "code": "BNlslBrAmuK",
    "comments": {
      "count": 32
    },
    "date": 1480841148,
    "dimensions": {
      "height": 1081,
      "width": 1080
    },
    "display_src": "https://scontent-fra3-1.cdninstagram.com/t51.2885-15/e35/15338533_742473602572119_6095178116286644224_n.jpg?ig_cache_key=MTM5NzcxOTMxNzgzMDg1NTU2Mg%3D%3D.2",
    "id": "1397719317830855562",
    "is_video": false,
    "likes": {
      "count": 1793
    },
    "owner": {
      "id": "1620542756"
    },
    "thumbnail_src": "https://scontent-fra3-1.cdninstagram.com/t51.2885-15/s640x640/sh0.08/e35/c0.0.1080.1080/15338533_742473602572119_6095178116286644224_n.jpg?ig_cache_key=MTM5NzcxOTMxNzgzMDg1NTU2Mg%3D%3D.2.c"
  }
```

There you'll have access to the picture url ("display_src"), the likes count, and the id of the owner (which is not the username, the username is not accessible directly this way).

**Comment by fredericofs** [comment]
Amazing work!
Is there any way to get username of each photo, or username from userid, without api tokens ?
All I could find is api way:

"http://instagram.com/developer/endpoints/users/#get_users -> https://api.instagram.com/v1/users/(user id)/?access_token=ACCESS-TOKEN. The response is JSON and the data you want is data.username"

**Comment by althonos** [comment]
There is a way without the API, it requires connecting to the page of each
media (which is a tad longer), i'll add a method to do that when i can.

**Comment by althonos** [comment]
Latest Github version / future pypi v0.3.0 now has a way to get the username for a media:
```python
import instaLooter
import tempfile

looter = instaLooter.InstaLooter(tempfile.mkdtemp(), hashtag="yourhashtag")
for media in looter.pages(with_pbar=False) # set to True if you want the progress bar to display
    owner_info = looter.get_owner_info(media["code"])
    ...
```

owner_info will be a dictionary with the following keys/values:
```json
{
    "username": "instagram",
     "is_unpublished": false,
     "requested_by_viewer": false,
     "followed_by_viewer": false,
     "blocked_by_viewer": false,
     "profile_pic_url": "https://scontent-fra3-1.cdninstagram.com/t51.2885-19/s150x150/14719833_310540259320655_1605122788543168512_a.jpg",
     "full_name": "Instagram",
     "has_blocked_viewer": false,
     "id": "25025320",
     "is_private": false
          },
```

so you can now get the actual username ("full_name" key) from the media.

**Comment by fredericofs** [comment]
Thank you! 
This project rocks!

**Comment by althonos** [comment]
ahah thanks ;)
