### ISSUE TITLE
Download images from a private perfil

### ISSUE THREAD

**Issue by dfr0** [althonos/InstaLooter#38]
I need put my username  on Instalooper for download images to the private perfil.

**Comment by verafide** [comment]
Use the `-c` parameter which can be seen [here](http://instalooter.readthedocs.io/en/latest/usage.html#credentials).

    $ instaLooter ... -c MYLOGIN:MYPASSWORD
    $ instaLooter ... -c MYLOGIN
    Password: # type MYPASSWORD privately here

**Comment by dfr0** [comment]
Oh sorry for my disparage, this work perfect..

**Comment by althonos** [comment]
Thanks for quick response @verafide.

**Comment by verafide** [comment]
Thank you for all your work @althonos  I'll gladly try and help people here when I can.
