### ISSUE TITLE
Problem with regular expression

### ISSUE THREAD

**Issue by ImAWizardLizard** [althonos/InstaLooter#4]
C:\Users\User\Documents>instaLooter -n franiothepug
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\instaLooter.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\instaLooter.py", line 135
    _RX_CSRFTOKEN_JSON = re.compile(rb'"csrf_token": "([a-zA-Z0-9]*)"')
                                                                     ^
SyntaxError: invalid syntax

Even with correct parameters for the command, this error still seems to come up even when specifying the directory

**Comment by althonos** [comment]
Hi there, I think you are using an old version since _RX_CSRFTOKEN_JSON was removed when I switched to requests instead of httplib.

So if you downloaded the latest from pip, I may have forgotten to pack a new release properly since last bugfixes :)

**Comment by althonos** [comment]
Yes my bad, I'll repack a v0.2.3 release before tomorrow.

**Comment by althonos** [comment]
Fixed, v0.2.3 is online.
