### ISSUE TITLE
[Feature request] Download multi-image posts

### ISSUE THREAD

**Issue by Bangaio64** [althonos/InstaLooter#40]
There's a new kind of post that includes multiple images. Instalooter currently only downloads the first one.
An example: https://www.instagram.com/p/BRCAHTQhIW2/
You can move through the pictures by pressing the side arrows.

**Comment by althonos** [comment]
This was already requested in #39 and was successfully implemented in v0.7.0, available online on PyPI. I just tried and running `instaLooter post BRCAHTQhIW2 .` successfully downloads 10 different pictures.

**Comment by Bangaio64** [comment]
I am having trouble getting all pictures when using the `-T {date}` option. Maybe I'm missing something obvious.

`Instalooter instagram -T {username}_{date}_{id} -v --time 2017-03-11:2017-03-10`
Downloads 6 files (only 1 of the multi-image post)

`Instalooter instagram -T {username}_{id} -v --time 2017-03-11:2017-03-10`
Downloads 8 files (correct behaviour)

Also it should be noted in the documentation that `{code}` is not unique anymore.

**Comment by pengKiina** [comment]
> Ah I was using an older version. However, I am having trouble getting all pictures when using the `-T {date}` option. Maybe I'm missing something obvious.
> 
> `Instalooter instagram -T {username}_{date}_{id} -v --time 2017-03-11:2017-03-10`
> Downloads 6 files (only 1 of the multi-image post)
> 
> `Instalooter instagram -T {username}_{id} -v --time 2017-03-11:2017-03-10`
> Downloads 8 files (correct behaviour)
> 
> Also it should be noted in the documentation that `{code}` is not unique anymore.
> 
> Thanks!

any workaround yet in 2020?
