### ISSUE TITLE
[Feature request] Download Videos only

### ISSUE THREAD

**Issue by liorlior** [althonos/InstaLooter#41]
From my understanding there is still no such option/feature built in to instalooter: 
Would it be possible to skip downloading the pictures of a given user or hashhtag but only download the videos? That would be amazing. Something like:

`--videos-only` or shortly:  `-vo `

**Comment by althonos** [comment]
Good point. It shouldn't be too difficult to implement considering the existing codebase.

**Comment by althonos** [comment]
Added in v0.8.0.
