### ISSUE TITLE
No medias found

### ISSUE THREAD

**Issue by Akanksha-Tiwari** [althonos/InstaLooter#43]
After running the command succesfully for some other hashtags, I get the following output and no media. Now, even for the cases for which it was running correctly, I am unable to download anything else. Am I missing something here ?

python -m instaLooter hashtag muhammadali ~/Desktop/Event_Summarization/TOMM/muhammadali/insta/3rdJune/ --add-metadata --template {id}.{likescount}--{commentscount}--{datetime} --time 2016-06-03:2016-06-03
Loading pages |  0%(488 of 60903)|#                                                                                                                                    |Elapsed Time: 0:06:53 |ETA: 14:13:0313:27:18 - WARNING - No medias found.
Loading pages |N/A%(0 of N/A)|

**Comment by nagualcode** [comment]
Now it is needed to login first, in order to have access to the media pages.
Code needs to be updated...

**Comment by RPSPandora** [comment]
you should use credential -c user:password 
work okay
`python -m instaLooter hashtag muhammadali dump -n 100 -m -T {username}-{code} -c user:password`

**Comment by althonos** [comment]
This is linked to #45, i'm closing this issue (since it's resolved in your case if you login) in favor of the general one.
