### ISSUE TITLE
(Question) How do I use login credentials when using from Python API?

### ISSUE THREAD

**Issue by nagualcode** [althonos/InstaLooter#46]
When using instaLooter python api (import instaLooter)
how do I login with my credentials?

**Comment by althonos** [comment]
Just use the login method of the InstaLooter object you create beforehand:
```python
from instaLooter import InstaLooter

looter = InstaLooter("/your/output/directory/if/any")
looter.login("YOURLOGIN", "YOURPASSWORD")
looter.download() 
# ... #
```

Make sure you also have a look at the [API Reference](http://instalooter.readthedocs.io/en/latest/api.html) if you have other questions !
