### ISSUE TITLE
[Question] How can I use filename templates from the instaLooter api?

### ISSUE THREAD

**Issue by nagualcode** [althonos/InstaLooter#47]
How do I get this same result as 
-T {username}-{likescount}-{width}x{height}.{id}
using the instaLooter python api?

**Comment by althonos** [comment]
In the [API Reference of the InstaLooter.__init__ method](http://instalooter.readthedocs.io/en/latest/api.html#instaLooter.InstaLooter.__init__), you can see there is a template keyword argument.

So to do the same as your question:
```python
from instaLooter import InstaLooter
looter = InstaLooter(directory="...", profile="...", template="{username}-{likescount}-{width}x{height}.{id}")
```
