### ISSUE TITLE
[Question] Running InstaLooter as a cronjob

### ISSUE THREAD

**Issue by Bigben83** [althonos/InstaLooter#49]
Can InstaLooter be run as a cron job like the following

`0 21 * * * instaLooter [user] /public_html/InstaLooter/downloads/[user] -T {username}_{datetime} -q -m -N`

**Comment by althonos** [comment]
No idea, I'm a systemd user 😉

**Comment by skftn** [comment]
Use an absolute path to instaLooter else it won't work.

`0 21 * * * /usr/local/bin/instaLooter [user] /public_html/InstaLooter/downloads/[user] -T {username}_{datetime} -q -m -N`

**Comment by pierrep** [comment]
Yes this would be totally possible. You can also write a bash script and run that instead, for a cleaner crontab line..

**Comment by althonos** [comment]
I added a page about this to the documentation (http://instalooter.readthedocs.io/en/latest/cron.html). You may also want to check the recent implementation of #17 (see http://instalooter.readthedocs.io/en/latest/batch.html) to avoid creating a script for more complicated use cases.
