### ISSUE TITLE
Error when using -T

### ISSUE THREAD

**Issue by Bangaio64** [althonos/InstaLooter#51]
instaLooter 0.8.1 | Python 3.6.0 | Windows 7 64
Some images fail to download when using -T

`Instalooter instagram -T {username}_{date}_{code} -v -n 50`
In my test, it downloaded 40 files.

Example of an error:
> Exception in thread Thread-12:
> Traceback (most recent call last):
>   File "c:\program files (x86)\python36-32\lib\site-packages\instaLooter\core.py", line 522, in _make_filename
>     assert value is not None
> AssertionError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:\program files (x86)\python36-32\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "c:\program files (x86)\python36-32\lib\site-packages\instaLooter\worker.py", line 44, in run
>     self._download_video(media)
>   File "c:\program files (x86)\python36-32\lib\site-packages\instaLooter\worker.py", line 109, in _download_video
>     video_name = os.path.join(self.directory, self.owner._make_filename(data))
>   File "c:\program files (x86)\python36-32\lib\site-packages\instaLooter\core.py", line 524, in _make_filename
>     media = self.get_post_info(media['code'])
> KeyError: 'code'

`Instalooter instagram -v -n 50` downloads 50 as expected.

**Comment by althonos** [comment]
Seems like this was linked with #50. Fixed in v0.8.2.
