### ISSUE TITLE
[Bug] --time parameter not working on large hashtags

### ISSUE THREAD

**Issue by althonos** [althonos/InstaLooter#52]
Described by @cyrusclarke: when using the `--time` flag on a tag with a lot of pictures/videos, the program returns and states that no media could be found.

**Comment by althonos** [comment]
@cyrusclarke: seems like this was caused by #53, after small tests it seems to be working back again. Please comment here otherwise.

**Comment by anobles1** [comment]
I think I have the same issue. When using the time arguments, I receive 'no medias found'. Example code: python -m instalooter hashtag wellness tar://wellness_1217.tar.gz --jobs 16 --dump-json --extended-dump --time 2017-12-01:2017-12-31
