### ISSUE TITLE
Massive date conversion bug after recent site updates

### ISSUE THREAD

**Issue by VasiliPupkin256** [althonos/InstaLooter#53]
instaLooter-0.8.2-py2

{date} filename template cause error:

> instalooter -v -T {date}_{id} -m ...

  File "...\site-packages\instaLooter\core.py", line 48, in <lambda>
    'date': lambda m: datetime.date.fromtimestamp(m['date']) if 'date' in m else None,
TypeError: an integer is required (got type NoneType)

It also throw errors without the {date} template (still download files though):

> instalooter -v -T {id} -m

  File "...\lib\threading.py", line 911, in _bootstrap_innerself.run()
  File "...\lib\site-packages\instaLooter\worker.py", line 46, in runself._download_photo(media)
  File "...\lib\site-packages\instaLooter\worker.py", line 94, in _download_photoself._add_metadata(photo_name, media)
  File "...\lib\site-packages\instaLooter\worker.py", line 77, in _add_metadatapiexif.ExifIFD.DateTimeOriginal: datetime.datetime.fromtimestamp(metadata['date']).isoformat(), 
TypeError: a float is required

**Comment by IHTFY** [comment]
I also saw the first error you mentioned, but it only seems to appear when trying to download a gallery/slideshow post. I know previously the photos in that group had identical datetime exif info because I was using that as my unique identifier and it was creating a moshed image of all the members in the slideshow. Maybe only one slide gets time info now?

**Comment by Bangaio64** [comment]
`Instalooter sony -T {username}--{date}[]{code}_{id} -v --time 2017-04-22:2017-04-15`

> Loading pages |N/A%(0 of 99)|                                                                        |Elapsed Time: 0:00:00 |ETA:  --:--:--←[35m17:58:45←[0m - ←[31mERROR←[0m - ←[39man integer is required (got type NoneType)←[0m
> Loading pages |100%(0 of N/A)|#                                                                      |Elapsed Time: 0:00:00 |ETA:  --:--:--
> Loading pages |100%(0 of N/A)|#                                                                      |Elapsed Time: 0:00:01 |ETA:  --:--:--
> Loading pages |100%(0 of N/A)|#                                                                      |Elapsed Time: 0:00:01 |ETA:  --:--:--

Some multi-image posts seem to be tripping it up.

I have observed videos saved with `None` as `{date}`, too.

**Comment by althonos** [comment]
I attempted a hotfix, seems like IG renamed the `date` field to `created_at_timestamp` in so-called "multiposts". At least, version `v0.9.1` doesn't crash when running the above command.

**Comment by VasiliPupkin256** [comment]
Why have you closed the bug? The issue isn't gone. It doesn't crash but throw errors from worker.py. Also as I understand you have just removed the `date` attribute but do not read `created_at_timestamp`.

**Comment by VasiliPupkin256** [comment]
Videos are now downloaded with 'None' string instead of correct datetime value for instance

**Comment by althonos** [comment]
I thought this only occured for multi-image posts. But this should be fixed in c804a378836a49289bb75a247c177eddad57c5ff.

**Comment by VasiliPupkin256** [comment]
Can confirm, the date bug is now fixed and seems to work fine in v0.9.3
