### ISSUE TITLE
key error: u'media'

### ISSUE THREAD

**Issue by nagualcode** [althonos/InstaLooter#54]
My goal is to get username, thumbnail url and likes count from photos of a given hashtag.
My code used to work fine, the last few days I started to get error:

Using:
` for mymedia in looter.medias(with_pbar=False, media_count=50):
    owner_info = looter.get_owner_info(mymedia["code"])
    likes = int(mymedia['likes']['count'])
    username = owner_info["username"]
    thumb_url = mymedia["thumbnail_src"].split("?")[0]
    purl = mymedia['display_src'].split("?")[0]`

Now I get:
    owner_info = looter.get_owner_info(mymedia["code"])
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/core.py", line 353, in get_owner_info
    return data['entry_data']['PostPage'][0]['media']['owner']
KeyError: u'media'

**Comment by dannyvoid** [comment]
Had the same issue until I manually updated InstaLooter this morning.

**Comment by nagualcode** [comment]
How did you updated?
pip install instaLooter --upgrade seems not enough here...

**Comment by althonos** [comment]
I'll push a hotfix this afternoon, I forgot to apply some changes I made to the previous edits.

**Comment by althonos** [comment]
Fixed in v0.9.0.
