### ISSUE TITLE
Commenter and Tagged Error

### ISSUE THREAD

**Issue by callmesquirrel** [althonos/InstaLooter#56]
The code examples in the documentation that describe how to get a set of all users that have commented on a profile no longer works. Same goes for getting tagged users. They no longer recognize the keys and return KeyErrors.

![image](https://cloud.githubusercontent.com/assets/27927476/25316715/6aaa9d84-283a-11e7-9812-be73a4ce4ba5.png)

**Comment by althonos** [comment]
Thanks, examples were replaced and should be working fine.
