### ISSUE TITLE
new feature - downlo multiple accounts with one login

### ISSUE THREAD

**Issue by rlyons** [althonos/InstaLooter#58]
The idea is that instead of logging in multiple times, you could login once.

format:

username:directory,username2:directory2,username3:directory3

you could test to see if it is a multiple user string by looking for the colon...

internally then,
{account1: directory1, account2: directory2}
and then loop through them....

**Comment by verafide** [comment]
Similar to Issue #17 the bash one-liner seen there has worked well for me.

**Comment by althonos** [comment]
@verafide: thanks 😉 

@rlyons: adding a CLI to do that would be tricky, so I will only support it through a custom yaml file. See #17 and just wait for my finals to be over 😃
