### ISSUE TITLE
[Question] Get different size and the description of the post

### ISSUE THREAD

**Issue by Tynyndil** [althonos/InstaLooter#60]
Hello!

First thanks a lot for your job! It actually helped me a lot.
I have two differents questions:
- Is it possible to get two different size of the image? Instagram API allow us to get a "standard_resolution", a "low_resolution" and a "thumbnail", is it possible to do approximately the same with InstaLooter?
- Can i get the description of the post? By that I mean get the first comment of the post wrote by the account owner. I tried many of your methods on my python scripts but it seems i can't... did I miss something or is it just actually impossible?

Sorry if i did mistakes in english : p

**Comment by verafide** [comment]
> Can i get the description of the post? By that I mean get the first comment of the post wrote by the account owner.

[`-m, --add-metadata`](http://instalooter.readthedocs.io/en/latest/usage.html#optional-arguments)
Add date, caption and authorship metadata to downloaded pictures. Requires PIL or Pillow as well as piexif.

Does that not do what you want?

**Comment by althonos** [comment]
@Tynyndil : I suppose you mean through the API ?
So for the description, you can't right now because IG itself changed the place their caption was in, so I have to change it.

For the two different sizes, indeed you can: dictionaries returned  by `instaLooter.get_post_info` or yielded by `instaLooter.medias` contain two url: `thumbnail_src` for the thumbnail and `display_src` for the full picture.

**Comment by Tynyndil** [comment]
Oh yeah didn't see that, but the problem is its actually just cuting the pictures to make a square, this is not really a low size of the picture. Or maybe i should go for a script which change the url to force a size, just before the /e35/, i think this is possible i'll give it a try.

Thanks for your answers :)

**Comment by Tynyndil** [comment]
If someone need it, its pretty dirty (my first time in python) but it works: This code get the instagram link, the picture link the small picture link:

```
from instaLooter import InstaLooter
import sys
import string

looter = InstaLooter(directory="desktop" ,profile="initiativescoeur"
                     ,get_videos="true")

with open("instagram_links.csv", "w+") as output:
    output.write('"instagram_link","picture_link","small_picture_link"\n')
    for media in looter.medias():
        url = media['code']
        url1 = media['display_src']
            
        if ('/e35') in url1:
            a,b = url1.split('/e35')
        else:
            a,b = url1.split('/e15')

        a = a.replace('/s1080x1080','')
        a = a.replace('/s750x750','')
        a = a.replace('/s640x640','')
        a = a.replace('/s480x480','')
        a = a.replace('/s320x320','')
        a += '/s320x320/e35'
        url2 = a + b
            
        output.write('"https://www.instagram.com/p/{}",'.format(url))
        output.write('"{}",'.format(url1))
        output.write('"{}"\n'.format(url2))

print("Done")
```

**Comment by althonos** [comment]
Nice for a first ! Just two things:

* Python has booleans, so the right keyword argument value is `get_videos=True` for the looter initialisation
* No need to give a directory to the InstaLooter instance if you just want some metadata

Just a tip: Python has regexes, so the work is actually a lot easier if you can get a regex that works (I test mines using [regex101](https://regex101.com/)).

```python
from instaLooter import InstaLooter
import re # the regex module

looter = InstaLooter(profile="xxxx", get_videos=True) 
cleaning_regex = re.compile(r"(s[0-9x]*/)?(e[0-9]*)/")

with open("instagram_links.csv", "w+") as output:
    output.write('"instagram_link","picture_link","small_picture_link"\n')
    for media in looter.medias():
        post_url = "https://www.instagram.com/p/{}".format(media["code"])
        picture_url = media['display_src']
        small_picture_url = cleaning_regex.sub('s320x320/', media['display_src'])
        
        output.write('"{}","{}","{}"\n'.format(post_url, picture_url, small_picture_url)
```

**Comment by althonos** [comment]
I added the previous script to the example page of the documentation. Closing.
