### ISSUE TITLE
[Feature request] Instagram Stories support

### ISSUE THREAD

**Issue by Lambik** [althonos/InstaLooter#65]
Hi,

Would this script work/be made to work with the relatively new concept of Stories?

Best regards!

**Comment by althonos** [comment]
Duplicate of #36, where I said I had no idea how to do it yet (I don't have an Instagram account actually). But any help is welcome !

**Comment by Lambik** [comment]
Oh dang sorry, I thought I had read all the previous issues and must've overlooked it. Didn't mean to be annoying!
