### ISSUE TITLE
[Bug] Error when extracting likescount or commentscount

### ISSUE THREAD

**Issue by douglasrizzo** [althonos/InstaLooter#66]
I'm on version 0.9.6. When I add `{likescount}` or `{commentscount}` to my `-T` argument, the tool crashes with the following error:

**ERROR - 'int' object has no attribute 'get'**

It doesn't work with every profile. Here is one that just gave me this error:

    instaLooter zuck . -T {username}_{likescount}_{date}_{id}

**Comment by althonos** [comment]
Hi, thanks for reporting this bug, it is fixed in version `0.9.7` and I added tests to make sure it doesn't occur anymore.
