### ISSUE TITLE
Downloading hashtags not working

### ISSUE THREAD

**Issue by roeleveld** [althonos/InstaLooter#67]
Something like `instaLooter hashtag puppies` or `python -m  instaLooter hashtag puppies`
gives
`WARNING - Could not find page of user: hashtag`
`WARNING - No medias found.`

Same results when using the credential flags.

**Comment by althonos** [comment]
This is because the place you found this is way out of date, this bug was patched in the last version, passing a directory is now mandatory (otherwise `docopt` will fail).

**Comment by roeleveld** [comment]
thanks

**Comment by dunning1** [comment]
Well, thank you for this useful tool...honestly. 

However, I encounter the same message when using the hashtag download:  
>python -m instaLooter hashtag boys d:\instaPhoto -n 20 -u xxxx -p xxxx

10:20:16 - WARNING - Could not find page of user: boys
10:20:16 - WARNING - No medias found.

Obviously, I have read all the previous issues mentioning this problem, and make sure that a credentials and a directory were added. If the hashtag function is out of date now? Many thanks for reply :)
