### ISSUE TITLE
'-T requires argument' when I attempt to use username and datetime template

### ISSUE THREAD

**Issue by applepanda** [althonos/InstaLooter#69]
If I run for example: 

`instaLooter instagram instapics -T {username}.{datetime} `

I get the following:

`-T requires argument

Usage:
    instaLooter <profile> [<directory>] [options]
    instaLooter hashtag <hashtag> <directory> [options]
    instaLooter post <post_token> <directory> [options]
    instaLooter (-h | --help | --version | --usage)`

**Comment by althonos** [comment]
1. Seems like you are using an old version
2. Have you tried with quotes, eg `instaLooter instagram instapics -T "{username}.{datetime}" ?

**Comment by applepanda** [comment]
I'm using the latest version (0.9.8), but putting the template in quotes worked. Thanks
