### ISSUE TITLE
error: unrecognized arguments: -c

### ISSUE THREAD

**Issue by disrupted** [althonos/InstaLooter#7]
I can't get the login method using the --credentials / -c argument to work. I have used the format `instaLooter some_channel folder -c my_username:my_pw` but it always throws an error message *unrecognized arguments: -c* at me. what am I doing wrong here?

**Comment by althonos** [comment]
Are you using the latest version ? Logging in is only possible since
version 0.3.0.

To check the version you're using, run instaLooter with the `--version`
argument.

**Comment by disrupted** [comment]
oh, you're right. apparently I am on v0.2.3, but I just did a fresh install using pip. anyways, I pulled from the GitHub repo now and it works. thanks :)

**Comment by althonos** [comment]
I may have had forgotten to upload v0.3.0 to PyPI. Glad it works now.
