### ISSUE TITLE
Hashtag download does not finish

### ISSUE THREAD

**Issue by zeshuaro** [althonos/InstaLooter#76]
So I initialised InstaLooter with a hashtag as below (I tried hashtags of aliaime and heidibibe):
`looter = InstaLooter(hashtag=tag)`

Then I tried to download all the media with:
`looter.download()`

However, it kept downloading for 30 minutes so I downloaded it again with a progress bar. The progress bar showed the loading pages process but after reaching the last page it still kept on going and did not finish the process (both current page and last page just kept on increasing). 

I was also keeping track of the number of files being downloaded and the number did not increase when half of the pages were loaded, so I assume all media had been looted at that time and should finish the download process?

**Comment by althonos** [comment]
Hi there, thank you for this report, this seem like an interesting issue.

I just checked with `aliaime`, and it seems that after some point IG continues sending back posts that are marked with a hashtag although they were sent already: after the 330th post or so, I sent me back a post that have already been seen. In the end, the page advertised 433 different posts, but I could not get all of them.

**Comment by althonos** [comment]
So as a bugfix, the best is probably to have a `unique everseen` pattern so I can stop the iteration when encountering a post for the second time.

**Comment by althonos** [comment]
Fixed !
