### ISSUE TITLE
[Question] Getting caption of a picture

### ISSUE THREAD

**Issue by jorigin2012** [althonos/InstaLooter#78]
Is there anyway to get caption for pictures as well? it would be nice to get them

**Comment by verafide** [comment]
-m, --add-metadata
[Add date and caption metadata to downloaded pictures (requires PIL or Pillow as well as piexif).](http://instalooter.readthedocs.io/en/latest/usage.html#options-files)

Is that not what you want?

**Comment by jorigin2012** [comment]
no i mean with python api

**Comment by althonos** [comment]
You can :
```python 
from instaLooter import InstaLooter
looter = InstaLooter(profile="instagram")
for m in looter.medias():
    info = looter.get_post_info(m["code"])
    print(info["caption"])
```

You have to call `get_post_info` since profile pages do not include captions, only post pages do.

**Comment by jorigin2012** [comment]
thank you!
