### ISSUE TITLE
Profile Picture

### ISSUE THREAD

**Issue by jorigin2012** [althonos/InstaLooter#79]
Hey. Thanks for this great tool. 
Can we get profile pictures as well? (with or without python api)

**Comment by althonos** [comment]
Depending on what you are scraping, you have two ways to proceed:

* If you are scraping a profile and want to download the profile pic as well, use the `get_metadata` method of the `InstaLooter` instance. This will return a dictionnary with `profile_pic_url_hd` among the keys. (this method is not yet available in the PyPI version, you'll have to grab the development version on github before v0.11.0 releases).
* If you want the profile picture of the owner of a given picture/video, use the `get_owner_info` method, giving as argument the *code* of the media; it will return the same dictionnary as above.

**Comment by jorigin2012** [comment]
Thank you very much
