### ISSUE TITLE
Wrong post count

### ISSUE THREAD

**Issue by gtrr34** [althonos/InstaLooter#8]
When downloading from a username it shows much less post than what the user has, and once downloading finished shows the post count correct and then done.
eg. Total posts 1500
downloading: 0% (0 of 170)
then
downloading: 10% (170 of 170) -> then 1500 of 1500 done

But only 170 downloaded.

**Comment by althonos** [comment]
Hi, thanks for feedback,
could you provide an example username where this occured, as well as checking InstaLooter's version with the `--version` argument ?

**Comment by gtrr34** [comment]
Version: instaLooter 0.3.0
I have tried random 3 user names the error is same

![1](https://cloud.githubusercontent.com/assets/24524771/21101445/9f8c4544-c092-11e6-9933-c2b1e0446de9.png)
![2](https://cloud.githubusercontent.com/assets/24524771/21101449/a55f2270-c092-11e6-89df-629f69362950.png)

**Comment by althonos** [comment]
I cannot reproduce the error on both my Windows and my Linux machines.
* What operating system are you using ?
* What python version are you using ?
* Are you trying to get medias from a public or private profile ?
* What are the arguments you ran InstaLooter with ?
* Does it change anything if you try the '--get-videos' argument ?

Without giving me at least one of the usernames that raised this error for you there's not much else that I can do, unfortunately...

**Comment by gtrr34** [comment]
- Linux raspberrypi 4.4.32+ #924
- Python 2.7.9
- Public user (Try username: gtr)
- Without any arguments: instaLooter gtr /home/pi/GTR
- `--get-videos` - didn't solve

![3](https://cloud.githubusercontent.com/assets/24524771/21101908/e51ad6dc-c094-11e6-9c52-774873efe7fc.png)

**Comment by gtrr34** [comment]
Try on different Server:
- Ubuntu 16.04.1 LTS
- Python 2.7.12

Same thing

![6](https://cloud.githubusercontent.com/assets/24524771/21102062/d73a8908-c095-11e6-8cbf-fb6a2e68c832.png)
![7](https://cloud.githubusercontent.com/assets/24524771/21102063/d73ac526-c095-11e6-8395-42e582a9e292.png)

**Comment by althonos** [comment]
Hum. Very peculiar indeed, I cannot reproduce anything.
I'll investigate, but that may take time and never produce any results. I keep you informed.

**Comment by gtrr34** [comment]
Does that username name give you the desired results on your systems?

**Comment by althonos** [comment]
Yes, I got a page count of 236, a download count of 2678 and 2678 downloaded files in my test folder.

**Comment by gtrr34** [comment]
Issue is solved,
WinSCP was showing incorrect number of files.
`find . -type f | wc -l` 
inside the folder displays the correct number of files.

Sorry for the trouble.

**Comment by althonos** [comment]
Nevermind, glad it works.
