### ISSUE TITLE
[Bug] Instalooter crashing with multiple errors when logging in

### ISSUE THREAD

**Issue by GFBsoul** [althonos/InstaLooter#80]
Instalooter has been running great on a Raspberry Pi with Raspbian Jessie for me until the 8th of July.
I just upgraded to version 0.10.2 and made sure it was the only version present and installed with pip3. Installed python version is 3.4.2 and python 2.7.9.

Here's the traceback:
> Traceback (most recent call last):
  File "/usr/local/bin/instalooter", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/dist-packages/instaLooter/utils.py", line 174, in new_func
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/instaLooter/cli.py", line 156, in main
    looter.login(username, password)
  File "/usr/local/lib/python3.4/dist-packages/instaLooter/core.py", line 213, in login
    raise SystemError("Login error: check your connection")
SystemError: Login error: check your connection

Thanks for your great work!

**Comment by althonos** [comment]
Seems like the login procedure did change. Does it work when you're using `instaLooter` without logging in ?

**Comment by GFBsoul** [comment]
Works fine without logging in. So, you are right about the login procedure.

**Comment by althonos** [comment]
@GFBsoul : I just did login successfully through the CLI. Are you still encountering this bug ?

**Comment by GFBsoul** [comment]
Just tried it, works fine now! Thanks!
