### ISSUE TITLE
Getting information for an instagram id

### ISSUE THREAD

**Issue by jorigin2012** [althonos/InstaLooter#81]
I know its possible to get user id for an username with python api, but can this be done vice-versa?  Some instagram users change their username and im wondering if there is anyway to get their new username with their user id? (Or get their media with id instead of username?)
Thank you very much for this great tool.

**Comment by althonos** [comment]
No, you can't do that in that order, since Instagram uses the `username <-> id` map internally. You could do it with an access to the IG API, but that's out of the scope of this program.

**Comment by jorigin2012** [comment]
Thanks for the replay.
I was checking around and i found this php scraper and they wrote in description:
"Instagram PHP Scraper. Get account information, photos, videos and comments **without any authorization**"
https://github.com/postaddictme/instagram-php-scraper

It has a "getAccountById" method which returns username
I dont know php that much and i was wondering if they are using api for this or not.
Please check them if you have some time.
Thank you.
(sorry for poor english)
