### ISSUE TITLE
Instagram image url changed

### ISSUE THREAD

**Issue by MohamedIM** [althonos/InstaLooter#82]
Unfortunately I've bad news for you. Instagram images url has been changed you no longer can remove the 2nd and 3rd components for resized images.
For example this image from **instagram** account:
https://ig-s-c-a.akamaihd.net/h-ak-igx/t51.2885-15/e35/19764472_1586345694718446_4011887281420894208_n.jpg
Cannot no longer be trimmed to:
https://ig-s-c-a.akamaihd.net/h-ak-igx/19764472_1586345694718446_4011887281420894208_n.jpg
Currently ```instaLooter``` cannot download images this this url format.

**Comment by althonos** [comment]
@MohamedIM : Thanks for report, I'll have a look when I can. Seems like https://ig-s-c-a.akamaihd.net/h-ak-igx/random-bullshit/19764472_1586345694718446_4011887281420894208_n.jpg works, though !

**Comment by althonos** [comment]
This is kinda weird, because even the picture you're refering to does not have the same `display_src` than the one you're giving me. So this may as well be a "special" url, since I cannot find any url of this format anywhere when scraping either the `instagram` profile or the `cake` hashtag.

**Comment by althonos** [comment]
I added a supplementary regex that will change the behaviour of the default url generator if `h-ak-igx` is found in the `display_src`.
