### ISSUE TITLE
5xx error

### ISSUE THREAD

**Issue by wucares** [althonos/InstaLooter#83]
First time using this so it's likely an error on my end but I can't figure it out.

Trying to download any images (I've tried a single post and by username) results in the images being "downloaded" and yet they're only 105 bytes big. Opening them in a text editor reveals it's the server spitting out a 5xx error (no other info.)

--traceback doesn't give an error and, surprisingly, adding -v leads to videos being downloaded successfully.

**Comment by althonos** [comment]
Duplicated with #82, this is caused by a change in the servers URLs. I'll fix it soon.

**Comment by wucares** [comment]
I thought it might be related. Thank you.
