### ISSUE TITLE
[Question] How to log out

### ISSUE THREAD

**Issue by Svekla** [althonos/InstaLooter#87]
I have two private accounts that I want to download using two different accounts, but when I run:
`instaLooter privateaccount2 privateaccount2 -m -v --username user2 --password pass2 -T {date}-{code}`
after running:
`instaLooter privateaccount1 privateaccount1 -m -v --username user1 --password pass1 -T {date}-{code}`
I get 
> 19:28:20 - SUCCESS - Already logged in.
> 19:28:23 - WARNING - Profile privateaccount2 is private, and you are not following it.
> 19:28:23 - WARNING - No medias found.

On older version I was using -c and it worked great, but I can't do it on latest version. How can I log out to use different account? Thank you for help and for this awesome program!

**Comment by althonos** [comment]
Yes, after #27 I made the cookies resilient, using a cookie jar in a temporary folder `/tmp/instaLooter` on UNIX, and I'm not sure where on Windows. You can remove this cookie file manually to "log" you out. In the future I'll probably add a `logout` subcommand to the CLI.

**Comment by althonos** [comment]
@Svekla : I added a ``logout`` subcommand, it will be available in version `v0.12.0`.
