### ISSUE TITLE
Can I download the description of photo?

### ISSUE THREAD

**Issue by sombek** [althonos/InstaLooter#92]
Is there anyway to download the user's first comment or description?

**Comment by aandergr** [comment]
You may try [Instaloader](https://instaloader.readthedocs.io/), which for every downloaded Post also stores the Post's _caption_ in a separate `.txt` file:
```
$ pip3 install instaloader
$ instaloader PROFILE
```

**Comment by althonos** [comment]
@sombek: @AndCycle proposed a Pull Request to dump the metadata associated with every post in JSON format next to the downloaded picture / video. Check #88 for more information :)

**Comment by althonos** [comment]
@sombek: starting from `v0.13.0`, you can dump the metadata of a post next to the video / file in JSON format using the `--dump-json` flag. It will contain the caption as well as the top comments, etc.
