### ISSUE TITLE
Can I download just the metadata?

### ISSUE THREAD

**Issue by heydenis** [althonos/InstaLooter#95]
Following what I see in #88, will be possible to download just the metadata and not the pictures? This for people doing research on time, or photo description, and have no need of the images.

**Comment by althonos** [comment]
If there's a will there's a way ! I'll implement that before merging #88.

**Comment by althonos** [comment]
You'll be able to use the `--dump-only` (and you'll probably want to use the `--extended-dump` flag too) starting from **v0.13.0**.
