### ISSUE TITLE
The app is not working 

### ISSUE THREAD

**Issue by antero10** [althonos/InstaLooter#97]
I just start using the line command today, and every time  i ran `python -m instaLooter instagram /tmp` the terminal hang and also show's me this error

![screen shot 2017-09-17 at 11 10 15 am](https://user-images.githubusercontent.com/4040060/30522107-ce8f4166-9b98-11e7-93bc-cb359bbdb731.png)

and after that nothing happens, i have to close my terminal to keep using it. the `--traceback` flag show's me this error:

![screen shot 2017-09-17 at 11 11 00 am](https://user-images.githubusercontent.com/4040060/30522110-e8b9893e-9b98-11e7-9200-6d85ff9f53c6.png)

But i'm not really sure what is happening? i tried to debug the code without any luck. # #

**Comment by althonos** [comment]
Hi there !
This is linked directly to #96 , which will be solved in `v0.13.1`. The issue here is you're having a version of `requests` that's too old. Try updating (`pip install --user requests -U`) to get the latest version, and that should solve your issue.

**Comment by althonos** [comment]
Fixed.

**Comment by antero10** [comment]
We should add this app with a `docker` container, is easy to manage the version of the script locally, i can add that if you want to @althonos

**Comment by sanjeevmagoo** [comment]
@antero10 
@althonos 

Was this containerised ever?
